# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Configure git credentials
      uses: OleksiyRudenko/gha-git-credentials@v1
      with:
        # <git-user-email@domain.com> (default: github-action@users.noreply.github.com)
        email: dileep.cheepurupalli@gmail.com
        # Git User Name (default: "GitHub Action")
        name: dcheepurupalli
        # GitHub Actor Username (default: github.actor)
        # GitHub Token (default: secrets.GITHUB_TOKEN)
        token: 8c39236237078430a808cf59abcf150a67f57426
    
    - name: Install and Build 🔧
      run: |
        npm install
        npm run build 
        npm run deploy
